### ISSUE TITLE
Compatibility with jsp2pd

### ISSUE THREAD

**Issue by odesenfans** [mhchia/py-libp2p-daemon-bindings#43]
As mentioned in #42 , the Go libp2p daemon (aka `p2pd`) is deprecated and not actively maintained anymore. An equivalent daemon written in JavaScript (`jsp2pd`) is under development: https://github.com/libp2p/js-libp2p-daemon. I recently created [a fork](https://github.com/odesenfans/py-libp2p-daemon-bindings) of this library to communicate with this new daemon from a Python application. `jsp2pd` uses the same protocol as `p2pd` to communicate with applications and is pretty much a drop-in replacement.

I had to make the following modifications:
* Modify the test utils to invoke jsp2pd correctly (the command line options are slightly different)
* Update the protobuf spec to include the latest feature (namely, peerstore)
* Deactivate (skip) some tests as the features are not implemented yet in jsp2pd (ex: pubsub list_peers, some DHT functions).

Additionally, I removed the dependency to py-libp2p as it is deprecated as well. This package only uses minor features of py-libp2pd so I simply copy-pasted the relevant files to make it work.

Some tests still fail for unknown reasons (might be bugs in jsp2pd, might be issues with the tests themselves expecting some behavior from the Go daemon), but otherwise the fork is already usable. I'd like to pursue the work started on this library as it is already rich in features and well tested. How can we work together to integrate these changes in a clean way?

**Comment by mhchia** [comment]
Thanks for elaborating on the current situation and good work on https://github.com/mhchia/py-libp2p-daemon-bindings/pull/42! It's really great to know that you're interested in continuing the work. It will be ideal to me if we can support both `jsp2pd` and `p2pd`. Even though `p2pd` is rather old and not maintained, it is rather stable and it still supports some methods that `jsp2pd` has not supported yet. If #42 is merged both of them should work with our client. To support them well, we can 1) add some config in `P2PClient` to let users know the available methods their daemon provides and 2) add tests targeting both daemons. What do you think? Let me gather some thoughts and get back to you more tomorrow.

**Comment by odesenfans** [comment]
I agree, this makes sense. It should be fairly easy to configure the tests to use both daemons and to advertise the different features based on the daemon + version. I'll take some time to think about this as well, let's discuss it in the coming days!

**Comment by mhchia** [comment]
I just saw `js-libp2p-daemon` referring the [spec](https://github.com/libp2p/js-libp2p-daemon#specs). We just need to make sure our client follows the spec as well.

> It should be fairly easy to configure the tests to use both daemons and to advertise the different features based on the daemon + version. 

Yeah, sadly I don't have the bandwidth to write the code right now. If you're interested in taking on the task, we can start by specifying the changes we're gonna make more and I can help review the code.

**Comment by odesenfans** [comment]
I'll take the task. I'm wrapping up a prototype using the client library. Expect a few PRs once I'm done with it.

**Comment by mhchia** [comment]
That's great, thanks! Let me know if any help is needed.

**Comment by odesenfans** [comment]
I opened two preliminary PRs:
* #45 removes the dependency from libp2p by adding the files that are required.
* #44 adds a .gitignore file, because that was missing and a bit annoying during development.

Two notes:
* I did what I thought was the right thing regarding the license of the libp2p files. Since it uses a dual Apache + MIT license, it should be fine but I'm not entirely sure.
* More importantly, this breaks compatibility with libp2p entirely. The snippet below in `p2pclient/libp2p_stubs/peer/id.py` is called twice if an application imports this file and its equivalent in libp2p. This triggers what I think is a bug in `multihash`. My 2 cents is that an application should not rely on both the daemon and libp2p. I can add something in the README until the bug in multihash is fixed and/or the essential bits from libp2p are isolated in a smaller package.

```
    multihash.FuncReg.register(
        IDENTITY_MULTIHASH_CODE, "identity", hash_new=lambda: IdentityHash()
    )
```

Regarding the rest of the development, a few observations:
* There's no foolproof way to determine the language and version of the P2P daemon. You can't make the hypothesis that the daemon is installed on the machine, it could be dockerized or even running on another host in some cases. So you can't run `p2pd --version` or `jsp2pd --version` in a subprocess.
* Given that the client-daemon protocol is well defined and unlikely to change too much, I'm not sure we should block features at the `p2pclient.Client` class level. Since most functions are already implemented for the Go daemon, it's more likely to block users from using the newest version of the JS daemon until we unblock the features in a new release, which is IMO a bit silly and a waste of time for everyone.

So, I suggest the following:
1. Implement a compatibility dictionary that lists the features available for each language and version. This dictionary can be used in the tests to determine whether we should run some test cases or not. This dictionary could also be used from the client to log a warning. If you'd like strict version checks, we could use a configuration variable like `check_daemon_version: bool` to enforce the version checks if enabled.
2. Propose a new request message to ask the daemon for its own version, and get it implemented in both daemons. This way we would be able to block features adequately.

What do you think?

**Comment by odesenfans** [comment]
I took the bull by the horns and opened a PR on pymultihash to fix the bug I found, so this should lift the compatibility issue with libp2p: https://github.com/ivilata/pymultihash/pull/14.

**Comment by mhchia** [comment]
> You can't make the hypothesis that the daemon is installed on the machine, it could be dockerized or even running on another host in some cases. So you can't run p2pd --version or jsp2pd --version in a subprocess.

Agreed. That's the reason we don't have `Daemon` class which spawns p2pd/jsp2pd right now. In https://github.com/mhchia/py-libp2p-daemon-bindings/issues/33 I intended to have this class only as an optional helper for users to run the daemons more easily but we can just close the issue.

> 1. Implement a compatibility dictionary that lists the features available for each language and version. This dictionary can be used in the tests to determine whether we should run some test cases or not. This dictionary could also be used from the client to log a warning. If you'd like strict version checks, we could use a configuration variable like check_daemon_version: bool to enforce the version checks if enabled.
> 2. Propose a new request message to ask the daemon for its own version, and get it implemented in both daemons. This way we would be able to block features adequately.

- (1) sounds good to me.
- (2) is the best option for me but it takes time for the proposal to be discussed and finalized even if it's accepted. 

IMO we can either do (1), or leave the UI as is if there are other priorities. And we can simultaneously propose (2) to js-libp2p team. A RPC like `version` which returns the daemon's information `(daemon name, daemon version, libp2p daemon spec version)` definitely makes sense.

**Comment by mhchia** [comment]
Fixed by https://github.com/mhchia/py-libp2p-daemon-bindings/pull/49
