### ISSUE TITLE
CI failed

### ISSUE THREAD

**Issue by mhchia** [mhchia/py-libp2p-daemon-bindings#46]
[CI failed](https://app.circleci.com/pipelines/github/mhchia/py-libp2p-daemon-bindings/59/workflows/28d7bb7a-fc3b-4c5a-9aa6-4036102bbe0b/jobs/144) when checking out the code. It doesn't seem to do with our code. We can check the reason later.

**Comment by odesenfans** [comment]
Fixed by the move to Github Actions and the decommissioning of CircleCI.
